
services:
  db:
    image: postgres:latest
    container_name: gotransact_db
    environment:
      POSTGRES_DB: "GOTRANSACT_DB"
      POSTGRES_USER: "TRELLIS"
      POSTGRES_PASSWORD: "TRELLIS123"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: gotransact_app
  #   env_file:
  #     - ./.env
  #   ports:
  #     - "8080:8080"

  #   depends_on:
  #     - db
  #   networks:
  #     - backend

  redis:
    container_name: gh_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

